#!/usr/bin/env python

import datetime
import sys

def main():
  args = sys.argv[1:]
  for arg in args:
    # strip off any milliseconds, microseconds, etc. off the end
    (sec, subsec) = (arg[:10], arg[10:])
    d = datetime.datetime.fromtimestamp(float(sec))
    if len(subsec) > 0:
      print "%s:%d" % (d, int(subsec))
    else:
      print d

if __name__ == '__main__':
  main()
