#!/usr/bin/env python

import datetime
import sys
try:
  import pytz
except ImportError:
  print >>sys.stderr, '-'*100
  print >>sys.stderr, ' **** Looks like you are missing pytz; try `pip install pytz` or `easy_install pytz` ****'
  print >>sys.stderr, '-'*100
  print >>sys.stderr
  raise

def main():
  args = sys.argv[1:]
  for arg in args:
    if '.' in arg:
      # if there is a decimal point, we assume it must be in units of "seconds"
      (sec, subsec) = (arg, "")
    else:
      # strip off any milliseconds, microseconds, etc. off the end
      (sec, subsec) = (arg[:10], arg[10:])

    local = datetime.datetime.fromtimestamp(float(sec))
    utc = datetime.datetime.fromtimestamp(float(sec), pytz.utc)
    if len(subsec) > 0:
      print '%s.%s local' % (local, subsec)
      print '%s.%s UTC' % (utc, subsec)
    else:
      print '%s local' % local
      print '%s UTC' % utc

if __name__ == '__main__':
  main()
