name: debugit

on:
  pull_request:
    types: [assigned,unassigned,edited,ready_for_review,review_requested,review_request_removed]
  pull_request_review:
  issue_comment:
    types:
      - created

jobs:
  debug-stuff:
    name: Debug Stuff
    runs-on: ubuntu-latest
    # for the issue_comments trigger, only run on PR comments, not issues (these both use the same trigger)
    if: ${{ !github.event.issue || github.event.issue.pull_request }}
    steps:
      - name: Clone git repo
        uses: actions/checkout@v2
      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number || github.event.pull_request.number }}
	env:
	  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Issue
        run: echo ${{ github.event.issue }}
      - name: Print PR
        run: echo ${{ github.event.issue.pull_request }}
      - name: Print issue number
        run: echo ${{ github.event.issue.number }}
      - name: Print bare PR number
        run: echo ${{ github.event.pull_request.number }}
      - name: Print effective PR number
        run: echo ${{ github.event.issue.number || github.event.pull_request.number }}
      - name: fail
        run: exit 2
