name: debugit

on:
  pull_request:
    types: [assigned,unassigned,edited,ready_for_review,review_requested,review_request_removed]
  pull_request_review:
  issue_comment:
    types:
      - created

jobs:
  debug-stuff:
    name: Debug Stuff
    runs-on: ubuntu-latest
    # for the issue_comments trigger, only run on PR comments, not issues (these both use the same trigger)
    # if: ${{ !github.event.issue || github.event.issue.pull_request }}
    steps:
      - name: Print1
        run: echo ${{ github.event.issue }}
      - name: Print2
        run: echo ${{ github.event.issue.pull_request }}
